export const products = [
  { id: "nb", name: "Cheap Discord Nitro Month", price: "4.80", image: "https://vevorstore.cc/images/nitro1m.gif" },
  { id: "nby", name: "Cheap Discord Nitro Year", price: "39.99", image: "https://vevorstore.cc/images/nitro1y.gif" },
  { id: "deco", name: "Cheap Discord Decorations / Effects", price: "2.49", image: "https://vevorstore.cc/images/deco.gif" },
  { id: "nameplates", name: "Cheap Discord Nameplates", price: "2.79", image: "https://vevorstore.cc/images/nameplate.gif" },
  { id: "boosts", name: "Cheap Discord Server Boosts", price: "8.30", image: "https://vevorstore.cc/images/bst.gif" },
  { id: "members", name: "Cheap Discord Members", price: "0.79", image: "https://vevorstore.cc/images/members.gif" },
  { id: "spotify", name: "Cheap Spotify Premium", price: "3.00", image: "https://vevorstore.cc/images/spotify.gif" },
  { id: "deezer", name: "Cheap Deezer Premium", price: "3.99", image: "https://vevorstore.cc/images/deezer.gif" },
  { id: "netflix", name: "Cheap Netflix Premium", price: "4.99", image: "https://vevorstore.cc/images/netflix.gif" },
  { id: "crunchyroll", name: "Cheap Crunchyroll Premium", price: "3.99", image: "https://vevorstore.cc/images/crunchy.gif" },
  { id: "chatgpt", name: "Cheap ChatGPT Premium", price: "4.99", image: "https://vevorstore.cc/images/chatgpt.gif" },
  { id: "perplexity", name: "Cheap Perplexity AI Premium", price: "9.99", image: "https://vevorstore.cc/images/perplexity.gif" },
  { id: "youtube", name: "Cheap Youtube Premium", price: "3.99", image: "https://vevorstore.cc/images/ytpremium.gif" },
  { id: "ytmusic", name: "Cheap Youtube Music Premium", price: "23.99", image: "https://vevorstore.cc/images/ytmusic.gif" },
  { id: "canva", name: "Cheap Canva Pro", price: "2.99", image: "https://vevorstore.cc/images/canva.gif" },
  { id: "prime", name: "Cheap Amazon Prime Video", price: "4.99", image: "https://vevorstore.cc/images/prime.gif" },
  { id: "geoguessr", name: "Cheap GeoGuessr", price: "4.49", image: "https://vevorstore.cc/images/geo.gif" },
  { id: "medal", name: "Cheap Medal TV", price: "4.49", image: "https://vevorstore.cc/images/medal.gif" },
];
